platform :ios, '9.0'

project 'RONAK.xcodeproj'

target 'RONAK' do

source 'https://github.com/CocoaPods/Specs.git'


  pod 'SDWebImage', '~>3.8'
  pod 'JSONModel'

use_frameworks!

pod 'SalesforceAnalytics', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceSDKCore', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartStore', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartSync', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'AFNetworking', '~> 3.0'
pod 'MARKRangeSlider'
pod 'SevenSwitch', '~> 2.1'
pod 'Fabric'
pod 'Crashlytics'
pod 'MagicalRecord', '~> 2.3'

post_install do | installer |
    print "SQLCipher: link Pods/Headers/sqlite3.h"
    system "mkdir -p Pods/Headers/Private && ln -s ../../SQLCipher/sqlite3.h Pods/Headers/Private"
end

end
