platform :ios, '9.0'

project 'RONAK.xcodeproj'

target 'RONAK' do

source 'https://github.com/CocoaPods/Specs.git'


  pod 'SDWebImage', '~>3.8'
  pod 'JSONModel'

use_frameworks!

pod 'SalesforceAnalytics', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SalesforceSDKCore', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartStore', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'SmartSync', :path => 'mobile_sdk/SalesforceMobileSDK-iOS'
pod 'AFNetworking', '~> 3.0'
pod 'UIDevice-PasscodeStatus', '~> 0.0.2'
pod 'MARKRangeSlider'
pod 'TOPasscodeViewController'

end
